const list = [
  {
    _id: "0",
    title: "Project 1",
    description: "This is the Project One",
    taskData: {
      toDoList: [
        {
          _id: "20",
          title: "Weekend Getaway Planning",
          description: "Plan a weekend getaway to a nearby resort.",
          dueDate: "2023-11-30",
          priority: "Medium",
          variant: "toDo",
          labels: ["Personal", "Travel"],
        },
        {
          _id: "21",
          title: "Marketing Campaign Analysis",
          description: "Analyze the results of the recent marketing campaign.",
          dueDate: "2023-12-01",
          priority: "Low",
          variant: "toDo",
          labels: ["Work", "Analysis"],
        },
        {
          _id: "22",
          title: "Home Garden Maintenance",
          description: "Take care of the home garden and plant new flowers.",
          dueDate: "2023-11-30",
          priority: "Medium",
          variant: "toDo",
          labels: ["Personal", "Home"],
        },
        {
          _id: "23",
          title: "Board Meeting Preparation",
          description:
            "Prepare materials and presentations for the upcoming board meeting.",
          dueDate: "2023-12-02",
          priority: "High",
          variant: "toDo",
          labels: ["Work", "Board Meeting"],
        },
        {
          _id: "24",
          title: "Community Volunteer Event",
          description:
            "Participate in a community volunteer event this weekend.",
          dueDate: "2023-12-04",
          priority: "Medium",
          variant: "toDo",
          labels: ["Personal", "Volunteer"],
        },
      ],
      inProgressList: [
        {
          _id: "39",
          title: "Holiday Travel Booking",
          description:
            "Book flights and accommodations for the holiday vacation.",
          dueDate: "2023-12-26",
          priority: "Medium",
          variant: "toDo",
          labels: ["Personal", "Travel"],
        },
        {
          _id: "40",
          title: "Year-End Review",
          description:
            "Conduct a year-end review and set goals for the next year.",
          dueDate: "2023-12-28",
          priority: "Low",
          variant: "toDo",
          labels: ["Personal", "Planning"],
        },
        {
          _id: "41",
          title: "Project Presentation",
          description:
            "Prepare a project presentation for the client meeting next week.",
          dueDate: "2023-12-30",
          priority: "High",
          variant: "toDo",
          labels: ["Work", "Client Meeting"],
        },
        {
          _id: "42",
          title: "Family Dinner",
          description: "Organize a family dinner for a special occasion.",
          dueDate: "2024-01-01",
          priority: "Medium",
          variant: "toDo",
          labels: ["Personal", "Family"],
        },
        {
          _id: "43",
          title: "New Year's Resolutions",
          description:
            "Reflect on the past year and set New Year's resolutions and goals.",
          dueDate: "2024-01-02",
          priority: "Low",
          variant: "toDo",
          labels: ["Personal", "Planning"],
        },
      ],
      doneList: [
        {
          _id: "34",
          title: "Charity Fundraising",
          description:
            "Organize a charity fundraising event for a local cause.",
          dueDate: "2023-12-16",
          priority: "Medium",
          variant: "toDo",
          labels: ["Personal", "Charity"],
        },
        {
          _id: "35",
          title: "Product Testing",
          description:
            "Conduct testing and quality assurance for the new product release.",
          dueDate: "2023-12-18",
          priority: "High",
          variant: "toDo",
          labels: ["Work", "Quality Assurance"],
        },
        {
          _id: "36",
          title: "Parent-Teacher Conference",
          description:
            "Attend the parent-teacher conference at your child's school.",
          dueDate: "2023-12-20",
          priority: "Medium",
          variant: "toDo",
          labels: ["Personal", "Education"],
        },
        {
          _id: "37",
          title: "Budget Planning",
          description: "Review and plan the household budget for the new year.",
          dueDate: "2023-12-22",
          priority: "Low",
          variant: "toDo",
          labels: ["Personal", "Finance"],
        },
        {
          _id: "38",
          title: "Product Launch Preparation",
          description: "Finalize preparations for the product launch event.",
          dueDate: "2023-12-24",
          priority: "High",
          variant: "toDo",
          labels: ["Work", "Product Launch"],
        },
      ],
    },
  },
  {
    _id: "1",
    title: "Project 2",
    description: "This is the Project Two",
    taskData: {
      toDoList: [
        {
          _id: "1",
          title: "Meeting with Client",
          description:
            "Discuss project requirements and scope with the client.",
          dueDate: "2023-11-15",
          priority: "High",
          variant: "toDo",
          labels: ["Work", "Client Meeting"],
        },
        {
          _id: "2",
          title: "Research and Report",
          description:
            "Research market trends and prepare a market analysis report.",
          dueDate: "2023-11-14",
          priority: "Medium",
          variant: "toDo",
          labels: ["Work", "Analysis"],
        },
        {
          _id: "3",
          title: "Gym Workout",
          description: "Hit the gym for a 1-hour workout session.",
          dueDate: "2023-11-16",
          priority: "Low",
          variant: "toDo",
          labels: ["Personal", "Health"],
        },
        {
          _id: "4",
          title: "Website Development",
          description:
            "Work on the new website's front-end design and user interface.",
          dueDate: "2023-11-13",
          priority: "High",
          variant: "toDo",
          labels: ["Work", "Development"],
        },
        {
          _id: "5",
          title: "Grocery Shopping",
          description: "Buy groceries for the week.",
          dueDate: "2023-11-14",
          priority: "Low",
          variant: "toDo",
          labels: ["Personal", "Shopping"],
        },
      ],
      inProgressList: [
        {
          _id: "6",
          title: "Dentist Appointment",
          description: "Visit the dentist for a routine check-up.",
          dueDate: "2023-11-15",
          priority: "Low",
          variant: "toDo",
          labels: ["Personal", "Health"],
        },
        {
          _id: "7",
          title: "Blog Post Writing",
          description:
            "Write a blog post on a topic related to artificial intelligence.",
          dueDate: "2023-11-17",
          priority: "Medium",
          variant: "toDo",
          labels: ["Work", "Content Creation"],
        },
        {
          _id: "8",
          title: "Business Trip Planning",
          description:
            "Plan the details of the upcoming business trip to New York.",
          dueDate: "2023-11-13",
          priority: "High",
          variant: "toDo",
          labels: ["Work", "Travel"],
        },
        {
          _id: "9",
          title: "Weekend Hiking Trip",
          description: "Plan a weekend hiking trip to the mountains.",
          dueDate: "2023-11-20",
          priority: "Low",
          variant: "toDo",
          labels: ["Personal", "Travel"],
        },
        {
          _id: "10",
          title: "Client Presentation",
          description: "Prepare a presentation for a client meeting next week.",
          dueDate: "2023-11-19",
          priority: "High",
          variant: "toDo",
          labels: ["Work", "Client Meeting"],
        },
      ],
      doneList: [
        {
          _id: "11",
          title: "Team Building Event",
          description: "Organize a team-building event for the department.",
          dueDate: "2023-11-22",
          priority: "Medium",
          variant: "toDo",
          labels: ["Work", "Event Planning"],
        },
        {
          _id: "12",
          title: "Home Repairs",
          description: "Fix the leaky faucet and repair the garage door.",
          dueDate: "2023-11-18",
          priority: "Low",
          variant: "toDo",
          labels: ["Personal", "Home"],
        },
        {
          _id: "13",
          title: "Content Marketing Strategy",
          description:
            "Review and update the content marketing strategy for the quarter.",
          dueDate: "2023-11-21",
          priority: "Medium",
          variant: "toDo",
          labels: ["Work", "Strategy"],
        },
        {
          _id: "14",
          title: "Book Club Meeting",
          description:
            "Prepare for the next book club meeting and select the next book to read.",
          dueDate: "2023-11-25",
          priority: "Low",
          variant: "toDo",
          labels: ["Personal", "Reading"],
        },
        {
          _id: "15",
          title: "Product Launch",
          description:
            "Coordinate the product launch event and marketing efforts.",
          dueDate: "2023-11-26",
          priority: "High",
          variant: "toDo",
          labels: ["Work", "Product Launch"],
        },
      ],
    },
  },
];
